create table if not exists public.user_colors (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  value text not null,
  new boolean not null default false,
  is_new boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, name)
);

alter table public.user_colors enable row level security;

drop policy if exists "user_colors_select_own" on public.user_colors;
create policy "user_colors_select_own"
on public.user_colors
for select
using (auth.uid() = user_id);

alter table public.user_colors
  add column if not exists new boolean not null default false;

drop policy if exists "user_colors_upsert_own" on public.user_colors;
create policy "user_colors_upsert_own"
on public.user_colors
for insert
with check (auth.uid() = user_id);

drop policy if exists "user_colors_update_own" on public.user_colors;
create policy "user_colors_update_own"
on public.user_colors
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "user_colors_delete_own" on public.user_colors;
create policy "user_colors_delete_own"
on public.user_colors
for delete
using (auth.uid() = user_id);
